version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_svc
    ports:
      - "5672:5672"
      - "15672:15672"

  question:
    build: ./question
    container_name: question_svc
    environment:
      - PORT=3002
      # External Azure MySQL Flexible Server 
      - MYSQL_HOST=myquestionsdbserver.mysql.database.azure.com
      - MYSQL_PORT=3306
      - MYSQL_USER=myadmin@myquestionsdbserver
      - MYSQL_PASSWORD=Chocostrawberry1!
      - MYSQL_DATABASE=questionsdb
    depends_on:
      - rabbitmq
    ports:
      - "3002:3002"

  etl:
    build: ./etl
    container_name: etl_svc
    environment:
      - RABBIT_HOST=rabbitmq_svc
      - RABBIT_QUEUE=SUBMITTED_QUESTIONS
      # External DB connection details
      - MYSQL_HOST=myquestionsdbserver.mysql.database.azure.com
      - MYSQL_PORT=3306
      - MYSQL_USER=myadmin@myquestionsdbserver
      - MYSQL_PASSWORD=Chocostrawberry1
      - MYSQL_DATABASE=questionsdb
    depends_on:
      - rabbitmq


volumes:
  mysql_data: