version: "3.8"

services:
  submit:
    build: .
    container_name: submit_svc
    environment:
      - PORT=3001
      # point to the private IP of question-vm for categories and queue
      - QUESTION_SERVICE_URL=http://<question-vm-private-ip>:3002
      - RABBIT_HOST=<question-vm-private-ip>
      - RABBIT_QUEUE=SUBMITTED_QUESTIONS
    ports:
      - "3001:3001"
                                                                                              